import { describe, expect, test } from "vitest";
import { readFileSync } from "node:fs";

describe("homepage composition", () => {
  test("keeps package metadata product-facing instead of hackathon-facing", () => {
    const source = readFileSync(new URL("../package.json", import.meta.url), "utf8");
    const pkg = JSON.parse(source) as { description: string };

    expect(pkg.description).toContain("buyer workflow proof");
    expect(pkg.description).toContain("deployable agent operations");
    expect(pkg.description).not.toMatch(/hackathon/i);
  });

  test("keeps the first-screen hero separate from the long proof workbench", () => {
    const source = readFileSync(new URL("../src/AppHome.tsx", import.meta.url), "utf8");
    const proofSummarySource = readFileSync(new URL("../src/MarketHeroProofSummary.tsx", import.meta.url), "utf8");
    const acceptanceContractSource = readFileSync(new URL("../src/MarketHeroAcceptanceContract.tsx", import.meta.url), "utf8");
    const unlockBriefSource = readFileSync(new URL("../src/MarketHeroUnlockBrief.tsx", import.meta.url), "utf8");
    const boardMemoPanelSource = readFileSync(new URL("../src/HomepageBuyerBoardMemoPanel.tsx", import.meta.url), "utf8");
    const heroStart = source.indexOf('className="market-sky"');
    const boardMemoStart = source.indexOf("homepage-buyer-board-memo", heroStart);
    const proofCommandStart = source.indexOf('className="homepage-proof-command-stack"', heroStart);
    const proofPreviewStart = source.indexOf('className="proof-transformation-hero', proofCommandStart);
    const workbenchStart = source.indexOf('className="homepage-proof-workbench"', proofPreviewStart);
    const proofEntryStart = source.indexOf('id="homepage-proof-entry"', workbenchStart);

    expect(heroStart).toBeGreaterThan(-1);
    expect(boardMemoStart).toBeGreaterThan(heroStart);
    expect(proofCommandStart).toBeGreaterThan(boardMemoStart);
    expect(proofPreviewStart).toBeGreaterThan(proofCommandStart);
    expect(workbenchStart).toBeGreaterThan(proofPreviewStart);
    expect(proofEntryStart).toBeGreaterThan(workbenchStart);

    const heroSource = source.slice(heroStart, boardMemoStart);
    const boardMemoSource = source.slice(boardMemoStart, proofCommandStart);
    const proofCommandSource = source.slice(proofCommandStart, proofPreviewStart);
    expect(heroSource).toContain("Verifiable buyer approval loop");
    expect(heroSource).toContain("Prove agent value before launch");
    expect(heroSource).toContain("Paste one workflow. Get a buyer room, proof blockers, terms, and receipts reviewers can verify.");
    expect(heroSource).toContain("market-hero-first-output-rail");
    expect(heroSource).toContain("firstOutputModeLabel");
    expect(heroSource).toContain("firstOutputProofLine");
    expect(heroSource).toContain("firstOutputBlockerLine");
    expect(heroSource).toContain("firstOutputBoardLine");
    expect(heroSource).toContain("MarketHeroUnlockBrief");
    expect(heroSource).toContain("shareGate={homepageShareGate}");
    expect(heroSource).toContain("measuredMonthlyValueYen={homeMeasuredRunSummary.measuredMonthlyValueYen}");
    expect(heroSource).toContain("proofReadyCount={homepageProofEntry.readyCount}");
    expect(heroSource).toContain("receiptChecksum={homepageOutcomeArtifact.packet.receipt.checksum}");
    expect(unlockBriefSource).toContain("Buyer-ready unlock");
    expect(unlockBriefSource).toContain("const firstRepair");
    expect(unlockBriefSource).toContain("measured value waits on");
    expect(unlockBriefSource).toContain("proof artifacts");
    expect(unlockBriefSource).toContain('aria-label="Buyer-ready unlock brief"');
    expect(unlockBriefSource).toContain("market-hero-unlock-brief");
    expect(unlockBriefSource).toContain("market-hero-unlock-action");
    expect(heroSource).toContain("heroMobileBuyerDecisionQuestion");
    expect(heroSource).toContain("First usable output");
    expect(heroSource).toContain("{firstOutputBlockerLine} before buyer send");
    expect(heroSource).toContain("market-hero-buyer-decision-snapshot");
    expect(heroSource).toContain("Buyer decision brief");
    expect(heroSource).toContain("heroBuyerDecisionBrief.headline");
    expect(heroSource).toContain("Recommended buyer decision");
    expect(heroSource).toContain("heroBuyerDecisionBrief.decisionLabel");
    expect(heroSource).toContain("heroBuyerDecisionBrief.primaryAction.label");
    expect(heroSource).toContain("Board memo");
    expect(heroSource).toContain("Buyer decision memo");
    expect(heroSource).toContain('href="#buyer-board-memo"');
    expect(heroSource).toContain("homepageShareGate.sendPacket.mode");
    expect(heroSource).toContain("market-hero-first-output-status");
    expect(heroSource).toContain("Launch evidence");
    expect(heroSource).toContain("Public proof report");
    expect(heroSource).toContain("homepageProofEntry.proofScore");
    expect(heroSource).toContain("homepageProofEntry.status");
    expect(heroSource).toContain("market-hero-first-output-meter");
    expect(heroSource).toContain("Evidence board");
    expect(heroSource).toContain("Scope, value, trust");
    expect(heroSource).toContain("homepageRouteLock.operatorLine");
    expect(heroSource).toContain("homepageRouteLock.status");
    expect(heroSource).toContain("buyerDecisionCockpitHref={buyerDecisionCockpitHref}");
    expect(heroSource).toContain("href={launchEvidenceHref}");
    expect(heroSource).toContain("href={buyerEvidenceBoardHref}");
    expect(heroSource).not.toContain("Buyer-visible proof");
    expect(heroSource).not.toContain("market-hero-output-strip");
    expect(heroSource).not.toContain("MarketHeroProofSummary");
    expect(heroSource).not.toContain("MarketHeroAcceptanceContract");
    expect(source).not.toContain("buildHomepageBuyerBoardMemo");
    expect(boardMemoPanelSource).toContain("buildHomepageBuyerBoardMemo");
    expect(source).toContain('const HomepageBuyerBoardMemoPanel = lazy(() => import("./HomepageBuyerBoardMemoPanel"))');
    expect(boardMemoSource).toContain("Preparing buyer decision memo");
    expect(boardMemoSource).toContain("Buyer board memo");
    expect(boardMemoSource).toContain("valueLens={homepageValueLens}");
    expect(boardMemoSource).toContain("proofEntry={homepageProofEntry}");
    expect(boardMemoSource).toContain("outcomeArtifact={homepageOutcomeArtifact}");
    expect(boardMemoSource).toContain("reviewerHandoffKit={homepageReviewerHandoffKit}");
    expect(boardMemoSource).toContain("onCopyText={copyTextToClipboard}");
    expect(boardMemoSource).not.toContain("HomepageValueLensPanel");
    expect(proofCommandSource).toContain("Proof workbench");
    expect(proofCommandSource).toContain("Close the blockers that decide if this can be shared");
    expect(proofCommandSource).toContain("The hero names the first usable output.");
    expect(proofCommandSource).toContain("homepage-proof-command-rail");
    expect(proofCommandSource).toContain("Proof workbench next actions");
    expect(proofCommandSource).toContain("proofWorkbenchVerifyLabel");
    expect(proofCommandSource).toContain("proofWorkbenchVerifyLine");
    expect(proofCommandSource).toContain("proofWorkbenchShareLine");
    expect(proofCommandSource).toContain("proofWorkbenchShareActionExternal");
    expect(proofCommandSource).toContain("onClick={verifyBuyerProofLinks}");
    expect(proofCommandSource).toContain("href={homepageShareGate.primaryActionHref}");
    expect(proofCommandSource).toContain("href={buyerDecisionCockpitHref}");
    expect(proofCommandSource).toContain("Live proof");
    expect(proofCommandSource).toContain("Buyer send");
    expect(proofCommandSource).toContain("Open buyer call");
    expect(proofCommandSource).toContain("Buyer-visible proof");
    expect(proofCommandSource).toContain("market-hero-output-strip");
    expect(proofCommandSource).toContain("MarketHeroProofSummary");
    expect(proofSummarySource).toContain("market-hero-live-check");
    expect(proofSummarySource).toContain("market-hero-live-results");
    expect(proofSummarySource).toContain("triageRows");
    expect(source).toContain("proofRepairDraft");
    expect(proofSummarySource).toContain("Repair public proof blockers");
    expect(proofSummarySource).toContain("Paste replacement URL");
    expect(proofSummarySource).toContain("Save & recheck");
    expect(proofSummarySource).toContain("Buyer send decision");
    expect(proofSummarySource).toContain("shareGateHeadline");
    expect(proofSummarySource).toContain("Public proof-to-decision route");
    expect(proofSummarySource).toContain("Launch evidence report");
    expect(proofSummarySource).toContain("Open buyer decision cockpit");
    expect(proofSummarySource).toContain("Buyer evidence board");
    expect(proofSummarySource).toContain("Gate checks");
    expect(proofSummarySource).toContain("shareGate.checks.map");
    expect(proofSummarySource).toContain("Buyer send repair plan");
    expect(proofSummarySource).toContain("shareGate.repairPlan.items.map");
    expect(proofCommandSource).toContain("publicDecisionRoute={{");
    expect(proofCommandSource).toContain("launchEvidenceHref");
    expect(proofCommandSource).toContain("buyerEvidencePackHref: buyerDecisionCockpitHref");
    expect(source).toContain('workspaceSharedRouteHref("/buyer-decision-cockpit"');
    expect(source).not.toContain("homepageBuyerDecisionCockpit.shareHref");
    expect(proofCommandSource).toContain("buyerEvidenceBoardHref");
    expect(source).toContain("const homepageShareGate = useMemo");
    expect(source).toContain("buildBuyerShareGate({");
    expect(source).toContain("proofVerification: proofVerification ?? undefined");
    expect(proofCommandSource).toContain("shareGate={{");
    expect(proofCommandSource).toContain("checks: homepageShareGate.checks.map");
    expect(proofCommandSource).toContain("repairPlan: {");
    expect(proofCommandSource).toContain("homepageShareGate.repairPlan.items.map");
    expect(source).toContain("mergeWorkflowProofIntake");
    expect(source).toContain("Live proof verification started");
    expect(source).toContain("void verifyBuyerProofLinksWithIntake(nextProofIntake)");
    expect(source).toContain("verifyBuyerProofLinksWithIntake");
    expect(proofCommandSource).toContain("MarketHeroAcceptanceContract");
    expect(acceptanceContractSource).toContain("buildBuyerPilotAcceptanceContract");
    expect(acceptanceContractSource).toContain("Acceptance contract");
    expect(acceptanceContractSource).toContain("Next repair");
    expect(acceptanceContractSource).toContain("Copy repair");
    expect(acceptanceContractSource).toContain("Paste proof URL");
    expect(acceptanceContractSource).toContain("Apply & verify");
    expect(acceptanceContractSource).toContain("buyer-pilot-acceptance-repair.md");
    expect(acceptanceContractSource).toContain("Copy terms");
    expect(acceptanceContractSource).toContain("buyer-pilot-acceptance-contract.md");
    expect(proofCommandSource).toContain("proofFields={BUYER_PILOT_PROOF_FIELDS}");
    expect(proofCommandSource).toContain("onApplyProofRepairDraft");
    expect(proofCommandSource).toContain("onVerifyProofLinks");
    expect(proofCommandSource).toContain("verifyBuyerProofLinks");
    expect(proofSummarySource).toContain("proofButtonLabel(proofVerifyStatus)");
    expect(proofSummarySource).toContain("public proof links verified live");
    expect(heroSource).toContain("hero-secondary-diligence");
    expect(heroSource).toContain("Buyer diligence lane");
    expect(heroSource).toContain("heroDiligenceOpen ? (");
    expect(heroSource).toContain("HeroAgentCardAuditLauncher");
    expect(heroSource).toContain("HeroOutcomeReplayStrip");
    expect(source).toContain('const HeroAgentCardAuditLauncher = lazy(() => import("./HeroAgentCardAuditLauncher"))');
    expect(source).toContain('const HeroOutcomeReplayStrip = lazy(() => import("./HeroOutcomeReplayStrip"))');
    expect(heroSource).toContain("HeroWorkflowIntakeConsolePanel");
    expect(heroSource).toContain("buyerDecisionCockpitHref={buyerDecisionCockpitHref}");
    expect(heroSource).toContain("launchEvidenceHref={launchEvidenceHref}");
    expect(heroSource).toContain("buyerEvidenceBoardHref={buyerEvidenceBoardHref}");
    expect(source).toContain("buildHomepageBuyerDecisionCockpitFromWorkspace");
    expect(source).toContain("workspaceForcedRouteHref");
    expect(source).toContain("buyerEvidenceResponseWorkspaceDraft");
    expect(source).toContain('importedFromShare || workspaceSource === "shared" ? initialWorkspace : workspaceDraft');
    expect(source).toContain("buyerEvidenceResponseRouteHrefs");
    expect(source).toContain('if (!importedFromShare && workspaceSource !== "shared") return null');
    expect(source).toContain("homepageBuyerEvidenceResponseCockpit");
    expect(source).toContain("homepageBuyerEvidenceResponseTarget");
    expect(source).toContain("buyerEvidenceResponseTarget={homepageBuyerEvidenceResponseTarget}");
    expect(heroSource).toContain("HomepageExternalReviewerDockPanel");
    expect(heroSource).not.toContain("Turn one workflow into a verifiable buyer approval loop");
    expect(heroSource).not.toContain("The AI agent builds");
    expect(heroSource).not.toContain("final submission gaps");
    expect(heroSource).not.toContain("AgentCardIntakePanel");
    expect(heroSource).not.toContain("HomepageFirstRunValueProofCommandPanel");
    expect(heroSource).not.toContain("HomepageValueLensPanel");
    expect(heroSource).not.toContain("HomepageHeroPacketVerifierPanel");
    expect(heroSource).not.toContain("HeroPublishabilityVerdict");

    const workbenchSource = source.slice(workbenchStart, proofEntryStart);
    expect(workbenchSource).toContain("HomepageFirstRunValueProofCommandPanel");
    expect(workbenchSource).toContain("HomepageValueLensPanel");
    expect(workbenchSource).toContain("HomepageHeroPacketVerifierPanel");
    expect(workbenchSource).toContain("HeroPublishabilityVerdict");
  });

  test("routes the public buyer cockpit without requiring an evidencePack URL payload", () => {
    const appSource = readFileSync(new URL("../src/App.tsx", import.meta.url), "utf8");
    const pageSource = readFileSync(new URL("../src/HomepageBuyerDecisionCockpitPage.tsx", import.meta.url), "utf8");
    const sharePageSource = readFileSync(new URL("../src/QuickBuyerEvidencePackSharePage.tsx", import.meta.url), "utf8");
    const styles = readFileSync(new URL("../src/styles.css", import.meta.url), "utf8");

    expect(appSource).toContain('pathName === "/buyer-decision-cockpit"');
    expect(appSource).toContain('lazy(() => import("./HomepageBuyerDecisionCockpitPage"))');
    expect(pageSource).toContain("buildHomepageBuyerDecisionCockpitFromWorkspace");
    expect(pageSource).toContain("decodeWorkspaceShareParam");
    expect(pageSource).toContain('workspaceRouteHref("/", workspaceParam, "quick-workflow-intake")');
    expect(pageSource).toContain("responseReturnHref: workspaceHomeHref");
    expect(pageSource).toContain("<QuickBuyerEvidencePackSharePage homeHref={homeHref} payloadText={payloadText} responseReturnHref={responseReturnHref} />");
    expect(pageSource).not.toContain("QUICK_BUYER_EVIDENCE_PACK_SHARE_PARAM");
    expect(sharePageSource).toContain('aria-label="Buyer proof answer deck"');
    expect(sharePageSource).toContain("Buyer proof answers");
    expect(sharePageSource).toContain("buildQuickBuyerEvidenceDisclosureBoundary");
    expect(sharePageSource).toContain('aria-label="Evidence disclosure boundary"');
    expect(sharePageSource).toContain("buildQuickBuyerEvidenceProcurementHandoff");
    expect(sharePageSource).toContain('aria-label="Global procurement handoff"');
    expect(sharePageSource).toContain("buildQuickBuyerEvidenceAdoptionRiskLedger");
    expect(sharePageSource).toContain('aria-label="Buyer adoption risk ledger"');
    expect(sharePageSource).toContain("Risk CSV");
    expect(sharePageSource).toContain("buildQuickBuyerEvidenceAdoptionRiskDispositionReceipt");
    expect(sharePageSource).toContain("buildQuickBuyerEvidenceAdoptionRiskDispositionOwnerHandoff");
    expect(sharePageSource).toContain("buildQuickBuyerEvidenceAdoptionRiskOwnerCloseoutReceipt");
    expect(sharePageSource).toContain("buildQuickBuyerEvidenceAdoptionRiskRecheckPacket");
    expect(sharePageSource).toContain("buildQuickBuyerEvidenceAdoptionRiskSendControlReceipt");
    expect(sharePageSource).toContain('aria-label="Buyer adoption risk disposition receipt"');
    expect(sharePageSource).toContain("Verify risk receipt");
    expect(sharePageSource).toContain('aria-label="Risk disposition owner handoff"');
    expect(sharePageSource).toContain("Email risk owner");
    expect(sharePageSource).toContain('aria-label="Risk owner closeout receipt"');
    expect(sharePageSource).toContain("runAdoptionRiskOwnerCloseoutVerification");
    expect(sharePageSource).toContain('aria-label="Risk owner closeout inline verification"');
    expect(sharePageSource).toContain('aria-label="Risk recheck packet"');
    expect(sharePageSource).toContain("Email recheck owner");
    expect(sharePageSource).toContain('aria-label="Buyer-send risk control"');
    expect(sharePageSource).toContain("runAdoptionRiskSendControlVerification");
    expect(sharePageSource).toContain("buildQuickBuyerEvidenceDecisionMeetingAgenda");
    expect(sharePageSource).toContain('aria-label="Buyer decision meeting agenda"');
    expect(sharePageSource).toContain("buildQuickBuyerEvidenceCommitteeMinutes");
    expect(sharePageSource).toContain('aria-label="Buyer committee minutes"');
    expect(sharePageSource).toContain("buildQuickBuyerEvidenceActivationPlan");
    expect(sharePageSource).toContain('aria-label="Buyer activation plan"');
    expect(sharePageSource).toContain("buildQuickBuyerEvidenceValueCheckpoint");
    expect(sharePageSource).toContain('aria-label="Buyer value checkpoint"');
    expect(sharePageSource).toContain("buildQuickBuyerEvidenceValueCheckpointReceipt");
    expect(sharePageSource).toContain('aria-label="Buyer value checkpoint receipt"');
    expect(sharePageSource).toContain("buildQuickBuyerEvidenceValueCheckpointOwnerHandoff");
    expect(sharePageSource).toContain('aria-label="Buyer value checkpoint owner handoff"');
    expect(sharePageSource).toContain("Handoff calendar");
    expect(sharePageSource).toContain("buildQuickBuyerEvidenceValueOwnerCloseoutReceipt");
    expect(sharePageSource).toContain('aria-label="Buyer value owner closeout receipt"');
    expect(sharePageSource).toContain("runValueOwnerCloseoutVerification");
    expect(sharePageSource).toContain('aria-label="Value owner closeout inline verification"');
    expect(sharePageSource).toContain('fetch("/api/receipt-verifier"');
    expect(sharePageSource).toContain("buildQuickBuyerEvidenceValueNextWindowPacket");
    expect(sharePageSource).toContain('aria-label="Buyer value next window packet"');
    expect(sharePageSource).toContain("buildQuickBuyerEvidenceAnswerBrief");
    expect(sharePageSource).toContain('aria-label="Buyer answer brief"');
    expect(sharePageSource).toContain("buyerProofQuestions.map");
    expect(styles).toContain(".quick-buyer-evidence-share-question-deck");
    expect(styles).toContain(".quick-buyer-evidence-share-question-deck-grid");
    expect(styles).toContain(".quick-buyer-evidence-share-disclosure-boundary");
    expect(styles).toContain(".quick-buyer-evidence-share-disclosure-boundary-items");
    expect(styles).toContain(".quick-buyer-evidence-share-procurement-handoff");
    expect(styles).toContain(".quick-buyer-evidence-share-procurement-handoff-routes");
    expect(styles).toContain(".quick-buyer-evidence-share-adoption-risk-ledger");
    expect(styles).toContain(".quick-buyer-evidence-share-adoption-risk-ledger-risks");
    expect(styles).toContain(".quick-buyer-evidence-share-adoption-risk-disposition");
    expect(styles).toContain(".quick-buyer-evidence-share-adoption-risk-disposition-options");
    expect(styles).toContain(".quick-buyer-evidence-share-adoption-risk-handoff");
    expect(styles).toContain(".quick-buyer-evidence-share-adoption-risk-handoff-tasks");
    expect(styles).toContain(".quick-buyer-evidence-share-adoption-risk-owner-closeout");
    expect(styles).toContain(".quick-buyer-evidence-share-adoption-risk-recheck");
    expect(styles).toContain(".quick-buyer-evidence-share-risk-send-control");
    expect(styles).toContain(".quick-buyer-evidence-share-meeting-agenda");
    expect(styles).toContain(".quick-buyer-evidence-share-meeting-agenda-items");
    expect(styles).toContain(".quick-buyer-evidence-share-committee-minutes");
    expect(styles).toContain(".quick-buyer-evidence-share-committee-minutes-decisions");
    expect(styles).toContain(".quick-buyer-evidence-share-activation-plan");
    expect(styles).toContain(".quick-buyer-evidence-share-activation-plan-steps");
    expect(styles).toContain(".quick-buyer-evidence-share-value-checkpoint");
    expect(styles).toContain(".quick-buyer-evidence-share-value-checkpoint-items");
    expect(styles).toContain(".quick-buyer-evidence-share-value-closeout");
    expect(styles).toContain(".quick-buyer-evidence-share-value-closeout-options");
    expect(styles).toContain(".quick-buyer-evidence-share-value-handoff");
    expect(styles).toContain(".quick-buyer-evidence-share-value-handoff-tasks");
    expect(styles).toContain(".quick-buyer-evidence-share-value-owner-closeout");
    expect(styles).toContain(".quick-buyer-evidence-share-value-owner-closeout-tasks");
    expect(styles).toContain(".quick-buyer-evidence-share-value-owner-closeout-verifier");
    expect(styles).toContain(".quick-buyer-evidence-share-value-next-window");
    expect(styles).toContain(".quick-buyer-evidence-share-value-next-window-steps");
    expect(styles).toContain(".quick-buyer-evidence-share-answer-brief");
    expect(styles).toContain(".quick-buyer-evidence-share-answer-brief-actions");
  });

  test("keeps the Agent Card audit launcher inside the expandable buyer diligence lane", () => {
    const appSource = readFileSync(new URL("../src/AppHome.tsx", import.meta.url), "utf8");
    const launcherSource = readFileSync(new URL("../src/HeroAgentCardAuditLauncher.tsx", import.meta.url), "utf8");

    expect(appSource).toContain("const [heroDiligenceOpen, setHeroDiligenceOpen] = useState(false)");
    expect(appSource).toContain('className="hero-secondary-diligence"');
    expect(appSource).toContain("Buyer diligence lane");
    expect(appSource).toContain("setHeroDiligenceOpen(event.currentTarget.open)");
    expect(appSource).toContain("heroDiligenceOpen ? (");
    expect(appSource).toContain('lazy(() => import("./HeroAgentCardAuditLauncher"))');
    expect(appSource).not.toContain("function HeroAgentCardAuditLauncher");
    expect(launcherSource).toContain("agentCardDiligenceHrefFor");
    expect(launcherSource).toContain("agentCardTrialPlanHrefFor");
    expect(launcherSource).toContain("agentCardShortlistHrefFor");
    expect(launcherSource).toContain("Check an agent before the pilot");
    expect(launcherSource).toContain("Public Agent Card URL");
    expect(launcherSource).toContain("Diligence");
    expect(launcherSource).toContain("Trial plan");
    expect(launcherSource).toContain("Shortlist");
    expect(launcherSource).toContain("Buyer proof task");
    expect(launcherSource).not.toContain("Import and hire");
    expect(launcherSource).not.toContain("Hired ");
  });

  test("keeps the phone hero focused on the first usable output", () => {
    const styles = readFileSync(new URL("../src/styles.css", import.meta.url), "utf8");
    const tabletWorkflowRule = styles.indexOf(".hero-workflow-intake-mobile-mount {\n    display: grid;");
    const mobileStart = styles.indexOf("@media (max-width: 520px)", tabletWorkflowRule);
    const nextMediaStart = styles.indexOf("@media", mobileStart + 1);
    const mobileSource = styles.slice(mobileStart, nextMediaStart);

    expect(styles).toContain(".market-hero-first-output-status.is-send");
    expect(styles).toContain(".market-hero-first-output-meter.is-attention");
    expect(styles).toContain(".market-hero-first-output-meter.is-blocked");
    expect(styles).toContain(".market-hero-unlock-brief");
    expect(styles).toContain(".market-hero-unlock-metrics");
    expect(styles).toContain(".market-hero-first-output-rail .market-hero-unlock-action");

    const proofSummaryOrder = mobileSource.search(/\.market-hero-output-strip\s*\{\s*order:\s*4;\s*\}/);
    const firstOutputOrder = mobileSource.search(/\.market-hero-first-output-rail\s*\{\s*order:\s*3;/);
    const acceptanceOrder = mobileSource.search(/\.market-hero-acceptance-contract\s*\{\s*order:\s*5;\s*\}/);
    const workflowHidden = mobileSource.search(/\.hero-workflow-intake-mobile-mount\s*\{\s*display:\s*none;\s*\}/);
    const diligenceOrder = mobileSource.search(/\.hero-secondary-diligence\s*\{\s*order:\s*6;\s*\}/);
    const mobileDecisionBrief = mobileSource.search(/\.market-hero-buyer-decision-snapshot\s*\{\s*grid-column:\s*1 \/ -1;\s*min-width:\s*0;\s*display:\s*grid;/);
    const proofCommandResponsive = styles.indexOf(".homepage-proof-command-stack-head,\n  .homepage-proof-command-rail,\n  .homepage-proof-command-stack-grid {\n    grid-template-columns: 1fr;");

    expect(tabletWorkflowRule).toBeGreaterThan(-1);
    expect(mobileStart).toBeGreaterThan(tabletWorkflowRule);
    expect(proofCommandResponsive).toBeGreaterThan(-1);
    expect(styles).toContain(".market-hero-buyer-decision-snapshot {\n  display: none;\n}");
    expect(styles).toContain(".homepage-proof-command-action.is-send");
    expect(styles).toContain(".homepage-proof-command-action.is-review");
    expect(styles).toContain(".homepage-proof-command-action.is-hold");
    expect(firstOutputOrder).toBeGreaterThan(-1);
    expect(mobileDecisionBrief).toBeGreaterThan(-1);
    expect(mobileDecisionBrief).toBeGreaterThan(firstOutputOrder);
    expect(mobileSource).toContain(".market-hero-unlock-brief {\n    grid-column: 1 / -1;\n    grid-template-columns: 1fr;");
    expect(mobileSource).toContain(".market-hero-unlock-metrics {\n    display: grid;\n    grid-template-columns: 1fr;");
    expect(proofSummaryOrder).toBeGreaterThan(-1);
    expect(proofSummaryOrder).toBeGreaterThan(firstOutputOrder);
    expect(acceptanceOrder).toBeGreaterThan(proofSummaryOrder);
    expect(workflowHidden).toBeGreaterThan(-1);
    expect(diligenceOrder).toBeGreaterThan(workflowHidden);
  });

  test("frames the lower Agent Card area as trial evaluation instead of agent shopping", () => {
    const appSource = readFileSync(new URL("../src/AppHome.tsx", import.meta.url), "utf8");
    const intakeSource = readFileSync(new URL("../src/AgentCardIntakePanel.tsx", import.meta.url), "utf8");

    expect(appSource).toContain("Evaluate agent capability");
    expect(appSource).toContain("No-key fallback");
    expect(intakeSource).toContain("Agent Card Trial Intake");
    expect(intakeSource).toContain("Import for trial");
    expect(intakeSource).toContain("Imported ${result.agent.name}");

    expect(appSource).not.toContain("能力でAIを雇う");
    expect(appSource).not.toContain("鍵なしfallback");
    expect(intakeSource).not.toContain("Agent Card Intake");
    expect(intakeSource).not.toContain("Import and hire");
    expect(intakeSource).not.toContain("Hired ${result.agent.name}");
  });

  test("frames reviewer-facing proof panels as product proof instead of demo theater", () => {
    const source = readFileSync(new URL("../src/AppHome.tsx", import.meta.url), "utf8");

    expect(source).toContain("Reviewer proof receipt");
    expect(source).toContain("Seal external proof");
    expect(source).toContain("Reviewer proof route");
    expect(source).toContain("30-second proof route");
    expect(source).toContain("Build proof route");
    expect(source).toContain("External reviewer proof shelf");
    expect(source).toContain("買い手の主導線を邪魔しないよう");
    expect(source).toContain("審査員向けツールを開く");
    expect(source).toContain("/judge-tools");
    expect(source).toContain("Reviewer command center");
    expect(source).toContain("Reviewer concierge");
    expect(source).toContain("Reviewer Route Lock");
    expect(source).toContain("Reviewer script");
    expect(source).toContain("外部レビュー担当者が最初に見る順番を固定します");
    expect(source).toContain("外部レビュー担当者・買い手・提出者の最初の1クリック");

    expect(source).not.toContain("Judge demo receipt");
    expect(source).not.toContain("Seal the demo");
    expect(source).not.toContain("Demo runway");
    expect(source).not.toContain("30-second judge route");
    expect(source).not.toContain("Run demo runway");
    expect(source).not.toContain("Judge first click proof shelf");
    expect(source).not.toContain("審査・提出・競合証拠は必要な時だけ開く");
    expect(source).not.toContain("Judge command center");
    expect(source).not.toContain("Judge command request failed");
    expect(source).not.toContain("Judge Route Lock");
    expect(source).not.toContain("Judge script");
    expect(source).not.toContain("Demo concierge");
    expect(source).not.toContain("Demo concierge request failed");
  });

  test("keeps the first-click proof strip reviewer-facing instead of contest-facing", () => {
    const source = readFileSync(new URL("../src/AppHome.tsx", import.meta.url), "utf8");
    const stripStart = source.indexOf("function JudgeFirstClickStrip");
    const stripEnd = source.indexOf("type JudgeEvidencePanelProps", stripStart);
    const stripSource = source.slice(stripStart, stripEnd);

    expect(stripStart).toBeGreaterThan(-1);
    expect(stripEnd).toBeGreaterThan(stripStart);
    expect(stripSource).toContain("公開証拠まで閉じる");
    expect(stripSource).toContain("Reviewer snapshot");
    expect(stripSource).toContain("Reviewer proof status");
    expect(stripSource).toContain("Primary reviewer proof links");
    expect(stripSource).toContain("Reviewer first-click proof pages");
    expect(stripSource).not.toContain("提出証拠");
    expect(stripSource).not.toContain("Judge snapshot");
    expect(stripSource).not.toContain("Judge proof status");
    expect(stripSource).not.toContain("Primary judge proof links");
    expect(stripSource).not.toContain("Judge first click proof pages");
  });

  test("gives the reviewer proof tools their own page, mounting the curated route board before the generators", () => {
    const source = readFileSync(new URL("../src/AppHome.tsx", import.meta.url), "utf8");
    const appSource = readFileSync(new URL("../src/App.tsx", import.meta.url), "utf8");
    const boardSource = readFileSync(new URL("../src/ReviewerProofRouteBoard.tsx", import.meta.url), "utf8");
    const pageStart = source.indexOf("function JudgeToolsPage");
    const pageEnd = source.indexOf("function ValueBlueprintPanel", pageStart);
    const pageSource = source.slice(pageStart, pageEnd);
    const boardMount = pageSource.indexOf("<ReviewerProofRouteBoard />");
    const workbenchBodyMount = pageSource.indexOf('className="evidence-shelf-workbench-body"');
    const panelMap = pageSource.indexOf("JUDGE_EVIDENCE_PANELS.map", workbenchBodyMount);

    expect(appSource).toContain('pathName === "/judge-tools"');
    expect(source).toContain('lazy(() => import("./ReviewerProofRouteBoard"))');
    expect(pageStart).toBeGreaterThan(-1);
    expect(pageEnd).toBeGreaterThan(pageStart);
    expect(boardSource).toContain("Curated public proof route");
    expect(boardSource).toContain("Reviewer route map");
    expect(boardSource).toContain("Primary reviewer route links");
    expect(boardMount).toBeGreaterThan(-1);
    expect(workbenchBodyMount).toBeGreaterThan(boardMount);
    expect(panelMap).toBeGreaterThan(workbenchBodyMount);
    expect(pageSource).not.toContain("Judge first click proof pages");
    expect(pageSource).not.toContain("Submission Launch");
  });

  test("surfaces the buyer send brief before the hidden evidence dossier", () => {
    const source = readFileSync(new URL("../src/AppHome.tsx", import.meta.url), "utf8");
    const panelSource = readFileSync(new URL("../src/BuyerPilotSendNotePanel.tsx", import.meta.url), "utf8");
    const surfaceStart = source.indexOf("function BuyerProofCommandSurface");
    const sendBriefMount = source.indexOf("<BuyerPilotSendNotePanel", surfaceStart);
    const dossierStart = source.indexOf('className={cx("buyer-proof-dossier"', surfaceStart);

    expect(source).toContain('lazy(() => import("./BuyerPilotSendNotePanel"))');
    expect(surfaceStart).toBeGreaterThan(-1);
    expect(sendBriefMount).toBeGreaterThan(surfaceStart);
    expect(dossierStart).toBeGreaterThan(sendBriefMount);
    expect(panelSource).toContain("Buyer send brief");
    expect(panelSource).toContain("Suggested message");
    expect(panelSource).toContain("Send note attachments");
    expect(panelSource).toContain("Open blocker");
    expect(panelSource).not.toMatch(/demo/i);
  });

  test("turns the full buyer share gate into an owner repair workbench", () => {
    const source = readFileSync(new URL("../src/AppHome.tsx", import.meta.url), "utf8");
    const styles = readFileSync(new URL("../src/styles.css", import.meta.url), "utf8");
    const shareGateStart = source.indexOf('id="buyer-share-gate"');
    const checksStart = source.indexOf('className="buyer-share-gate-checks"', shareGateStart);
    const repairPlanStart = source.indexOf('className={cx("buyer-share-repair-plan"', shareGateStart);
    const proofRepairStart = source.indexOf('className="buyer-share-proof-repair"', repairPlanStart);
    const sendPacketStart = source.indexOf('className={cx("buyer-share-send-packet"', shareGateStart);
    const commandCenterMount = source.indexOf("<BuyerPilotCommandCenter");
    const commandCenterEnd = source.indexOf("/>", commandCenterMount);
    const commandCenterProps = source.slice(commandCenterMount, commandCenterEnd);

    expect(shareGateStart).toBeGreaterThan(-1);
    expect(checksStart).toBeGreaterThan(shareGateStart);
    expect(repairPlanStart).toBeGreaterThan(checksStart);
    expect(proofRepairStart).toBeGreaterThan(repairPlanStart);
    expect(proofRepairStart).toBeLessThan(sendPacketStart);
    expect(sendPacketStart).toBeGreaterThan(repairPlanStart);
    expect(commandCenterMount).toBeGreaterThan(-1);
    expect(source).toContain('aria-label="Buyer send repair plan"');
    expect(source).toContain("shareGate.repairPlan.exportHref");
    expect(source).toContain("shareGate.repairPlan.items.map");
    expect(source).toContain("Open repair target");
    expect(source).toContain("No open repair work");
    expect(source).toContain("shareGateProofRepairItem");
    expect(source).toContain("shareGateProofRepairField");
    expect(source).toContain("proofRepairDraft[shareGateProofRepairField.key]");
    expect(source).toContain("onProofRepairDraftChange(shareGateProofRepairField.key");
    expect(source).toContain("onApplyProofRepairDraft(shareGateProofRepairField.key)");
    expect(source).toContain("Save & recheck");
    expect(commandCenterProps).toContain("proofRepairDraft={proofRepairDraft}");
    expect(commandCenterProps).toContain("onProofRepairDraftChange={updateProofRepairDraft}");
    expect(commandCenterProps).toContain("onApplyProofRepairDraft={applyProofRepairDraft}");
    expect(styles).toContain(".buyer-share-repair-plan");
    expect(styles).toContain(".buyer-share-repair-items");
    expect(styles).toContain(".buyer-share-proof-repair");
    expect(styles).toContain(".buyer-share-repair-head .icon-link");

    const mobileShareGateStart = styles.indexOf(".buyer-share-gate {\n    order: 9;");
    const mobileStart = styles.lastIndexOf("@media", mobileShareGateStart);
    const nextMediaStart = styles.indexOf("@media", mobileShareGateStart + 1);
    const mobileSource = styles.slice(mobileStart, nextMediaStart);
    expect(mobileSource).toContain(".buyer-share-repair-head {\n    grid-template-columns: 1fr;");
    expect(mobileSource).toContain(".buyer-share-repair-items {\n    grid-template-columns: 1fr;");
    expect(mobileSource).toContain(".buyer-share-proof-repair {\n    grid-template-columns: 1fr;");
    expect(mobileSource).toContain(".buyer-share-proof-repair input,\n  .buyer-share-proof-repair button {\n    width: 100%;");
  });

  test("surfaces a buyer claim trace brief inside the proof command", () => {
    const appSource = readFileSync(new URL("../src/AppHome.tsx", import.meta.url), "utf8");
    const styles = readFileSync(new URL("../src/styles.css", import.meta.url), "utf8");
    const componentStart = appSource.indexOf("function BuyerProofClaimTraceStrip");
    const componentEnd = appSource.indexOf("function BuyerProofCommandSurface", componentStart);
    const componentSource = appSource.slice(componentStart, componentEnd);
    const surfaceStart = appSource.indexOf("function BuyerProofCommandSurface");
    const surfaceEnd = appSource.indexOf("function routeActionAttrs", surfaceStart);
    const surfaceSource = appSource.slice(surfaceStart, surfaceEnd);
    const renderStart = appSource.indexOf("<BuyerProofCommandSurface");
    const renderEnd = appSource.indexOf("/>", renderStart);
    const renderSource = appSource.slice(renderStart, renderEnd);

    expect(appSource).toContain("buildBuyerEvidenceTrace");
    expect(appSource).toContain("const homepageEvidenceTrace = useMemo");
    expect(appSource).toContain("buildBuyerEvidenceTrace({ room: launchRoom, shareGate: homepageShareGate })");
    expect(componentStart).toBeGreaterThan(-1);
    expect(componentEnd).toBeGreaterThan(componentStart);
    expect(componentSource).toContain('aria-label="Buyer claim trace brief"');
    expect(componentSource).toContain("evidenceTrace.claims.map");
    expect(componentSource).toContain("Audit checks");
    expect(componentSource).toContain("Approval trail");
    expect(componentSource).toContain("Next trace repair");
    expect(componentSource).toContain("Public trace");
    expect(componentSource).toContain("Repair blocker");
    expect(surfaceSource).toContain("<BuyerProofClaimTraceStrip evidenceTrace={evidenceTrace} evidenceTraceHref={evidenceTraceHref} />");
    expect(renderSource).toContain("evidenceTrace={homepageEvidenceTrace}");
    expect(renderSource).toContain("evidenceTraceHref={buyerEvidenceTraceHref}");
    expect(styles).toContain(".buyer-proof-claim-trace-strip");
    expect(styles).toContain(".buyer-proof-claim-trace-metrics");
    expect(styles).toContain(".buyer-proof-claim-trace-claims");
    expect(styles).toContain(".buyer-proof-claim-trace-claims {\n    grid-template-columns: repeat(3, minmax(0, 1fr));");

    const mobileTraceRule = styles.indexOf(".buyer-proof-claim-trace-strip {\n    grid-template-columns: 1fr;");
    const mobileStart = styles.lastIndexOf("@media", mobileTraceRule);
    const nextMediaStart = styles.indexOf("@media", mobileTraceRule + 1);
    const mobileSource = styles.slice(mobileStart, nextMediaStart);
    expect(mobileTraceRule).toBeGreaterThan(-1);
    expect(mobileSource).toContain(".buyer-proof-claim-trace-strip {\n    grid-template-columns: 1fr;");
    expect(mobileSource).toContain(".buyer-proof-claim-trace-metrics,\n  .buyer-proof-claim-trace-claims {\n    grid-column: auto;\n    grid-template-columns: repeat(2, minmax(0, 1fr));");
  });

  test("turns claim trace data into a buyer proof answer deck", () => {
    const appSource = readFileSync(new URL("../src/AppHome.tsx", import.meta.url), "utf8");
    const deckSource = readFileSync(new URL("../src/BuyerProofAnswerDeck.tsx", import.meta.url), "utf8");
    const styles = readFileSync(new URL("../src/BuyerProofAnswerDeck.css", import.meta.url), "utf8");
    const surfaceStart = appSource.indexOf("function BuyerProofCommandSurface");
    const surfaceEnd = appSource.indexOf("function routeActionAttrs", surfaceStart);
    const surfaceSource = appSource.slice(surfaceStart, surfaceEnd);

    expect(appSource).toContain('const BuyerProofAnswerDeck = lazy(() => import("./BuyerProofAnswerDeck"))');
    expect(deckSource).toContain('aria-label="Buyer proof answer deck"');
    expect(surfaceSource).toContain("<BuyerProofAnswerDeck evidenceTrace={evidenceTrace} evidenceTraceHref={evidenceTraceHref} onCopyText={onCopyText} />");
    expect(deckSource).toContain("buildBuyerProofAnswerDeckMarkdown");
    expect(deckSource).toContain("Question: ${claim.buyerQuestion}");
    expect(deckSource).toContain("Evidence answer: ${claim.verification}");
    expect(deckSource).toContain("Send rule: ${answerStateLine(claim)}");
    expect(deckSource).toContain("Copy answers");
    expect(deckSource).toContain("Download answers");
    expect(deckSource).toContain("evidenceTrace.claims.map");
    expect(deckSource).toContain('aria-label="Evidence-backed buyer answers"');
    expect(styles).toContain(".buyer-proof-answer-deck");
    expect(styles).toContain(".buyer-proof-answer-list");
    expect(styles).toContain(".buyer-proof-answer-list {\n    grid-template-columns: repeat(2, minmax(0, 1fr));");

    const mobileRule = styles.indexOf(".buyer-proof-answer-deck,\n  .buyer-proof-answer-deck-head,\n  .buyer-proof-answer-list {\n    grid-template-columns: 1fr;");
    const mobileStart = styles.lastIndexOf("@media", mobileRule);
    const mobileSource = styles.slice(mobileStart);
    expect(mobileRule).toBeGreaterThan(-1);
    expect(mobileSource).toContain(".buyer-proof-answer-deck-actions a,\n  .buyer-proof-answer-deck-actions button,\n  .buyer-proof-answer-card footer a {\n    width: 100%;");
  });

  test("shows a launch readiness lane between trace and answer deck", () => {
    const appSource = readFileSync(new URL("../src/AppHome.tsx", import.meta.url), "utf8");
    const laneSource = readFileSync(new URL("../src/BuyerLaunchReadinessLane.tsx", import.meta.url), "utf8");
    const styles = readFileSync(new URL("../src/BuyerLaunchReadinessLane.css", import.meta.url), "utf8");
    const surfaceStart = appSource.indexOf("function BuyerProofCommandSurface");
    const surfaceEnd = appSource.indexOf("function routeActionAttrs", surfaceStart);
    const surfaceSource = appSource.slice(surfaceStart, surfaceEnd);
    const traceMount = surfaceSource.indexOf("<BuyerProofClaimTraceStrip");
    const laneMount = surfaceSource.indexOf("<BuyerLaunchReadinessLane");
    const answerMount = surfaceSource.indexOf("<BuyerProofAnswerDeck");

    expect(appSource).toContain('const BuyerLaunchReadinessLane = lazy(() => import("./BuyerLaunchReadinessLane"))');
    expect(laneSource).toContain("buildBuyerLaunchReadinessLane");
    expect(laneSource).toContain("buildBuyerLaunchReadinessLaneMarkdown");
    expect(laneSource).toContain("Show the shortest path from draft room to external review");
    expect(laneSource).toContain("Value evidence");
    expect(laneSource).toContain("Measured run");
    expect(laneSource).toContain("Public proof");
    expect(laneSource).toContain("Scope and controls");
    expect(laneSource).toContain("Decision record");
    expect(laneSource).toContain("Copy lane");
    expect(laneSource).toContain("Download lane");
    expect(laneSource).toContain('aria-label="Buyer launch readiness lane"');
    expect(laneSource).toContain('aria-label="Selected launch readiness proof"');
    expect(surfaceSource).toContain("<BuyerLaunchReadinessLane evidenceTrace={evidenceTrace} evidenceTraceHref={evidenceTraceHref} onCopyText={onCopyText} />");
    expect(traceMount).toBeGreaterThan(-1);
    expect(laneMount).toBeGreaterThan(traceMount);
    expect(answerMount).toBeGreaterThan(laneMount);
    expect(styles).toContain(".buyer-launch-readiness-lane");
    expect(styles).toContain(".buyer-launch-stage-list");
    expect(styles).toContain(".buyer-launch-stage-list {\n    grid-template-columns: repeat(3, minmax(0, 1fr));");

    const mobileRule = styles.indexOf(".buyer-launch-readiness-lane,\n  .buyer-launch-readiness-head,\n  .buyer-launch-stage-list,\n  .buyer-launch-stage-body {\n    grid-template-columns: 1fr;");
    const mobileStart = styles.lastIndexOf("@media", mobileRule);
    const mobileSource = styles.slice(mobileStart);
    expect(mobileRule).toBeGreaterThan(-1);
    expect(mobileSource).toContain(".buyer-launch-readiness-actions a,\n  .buyer-launch-readiness-actions button,\n  .buyer-launch-stage-links a {\n    width: 100%;");
  });

  test("keeps mid-page reviewer artifacts out of the AppHome startup chunk", () => {
    const appSource = readFileSync(new URL("../src/AppHome.tsx", import.meta.url), "utf8");
    const artifactSource = readFileSync(new URL("../src/HomepageOutcomeArtifactPanel.tsx", import.meta.url), "utf8");
    const reviewerSource = readFileSync(new URL("../src/HomepageReviewerHandoffKitPanel.tsx", import.meta.url), "utf8");
    const globalStyles = readFileSync(new URL("../src/styles.css", import.meta.url), "utf8");
    const artifactStyles = readFileSync(new URL("../src/HomepageOutcomeArtifactPanel.css", import.meta.url), "utf8");
    const reviewerStyles = readFileSync(new URL("../src/HomepageReviewerHandoffKitPanel.css", import.meta.url), "utf8");
    const renderStart = appSource.indexOf("<HomepageOutcomeArtifactPanel");
    const reviewerStart = appSource.indexOf("<HomepageReviewerHandoffKitPanel");

    expect(appSource).not.toContain('import { HomepageOutcomeArtifactPanel } from "./HomepageOutcomeArtifactPanel"');
    expect(appSource).toContain('const HomepageOutcomeArtifactPanel = lazy(() => import("./HomepageOutcomeArtifactPanel").then((module) => ({ default: module.HomepageOutcomeArtifactPanel })))');
    expect(appSource).toContain('const HomepageReviewerHandoffKitPanel = lazy(() => import("./HomepageReviewerHandoffKitPanel"))');
    expect(appSource).toContain('aria-label="Buyer-facing artifact"');
    expect(appSource).toContain('aria-label="Reviewer handoff kit"');
    expect(renderStart).toBeGreaterThan(-1);
    expect(reviewerStart).toBeGreaterThan(renderStart);
    expect(artifactSource).toContain("Verify packet");
    expect(artifactSource).toContain("Packet receipt");
    expect(reviewerSource).toContain("Reviewer handoff kit");
    expect(reviewerSource).toContain("reviewer-handoff-kit.md");
    expect(artifactSource).toContain('import "./HomepageOutcomeArtifactPanel.css"');
    expect(reviewerSource).toContain('import "./HomepageReviewerHandoffKitPanel.css"');
    expect(globalStyles).not.toContain(".homepage-outcome-artifact");
    expect(globalStyles).not.toContain(".homepage-reviewer-kit");
    expect(artifactStyles).toContain(".homepage-outcome-artifact");
    expect(artifactStyles).toContain("@media (max-width: 640px)");
    expect(reviewerStyles).toContain(".homepage-reviewer-kit");
    expect(reviewerStyles).toContain("@media (max-width: 640px)");
  });

  test("keeps first-run value proof command styles with its lazy panel", () => {
    const appSource = readFileSync(new URL("../src/AppHome.tsx", import.meta.url), "utf8");
    const panelSource = readFileSync(new URL("../src/HomepageFirstRunValueProofCommandPanel.tsx", import.meta.url), "utf8");
    const globalStyles = readFileSync(new URL("../src/styles.css", import.meta.url), "utf8");
    const panelStyles = readFileSync(new URL("../src/HomepageFirstRunValueProofCommandPanel.css", import.meta.url), "utf8");

    expect(appSource).toContain('const HomepageFirstRunValueProofCommandPanel = lazy(() => import("./HomepageFirstRunValueProofCommandPanel"))');
    expect(panelSource).toContain('import "./HomepageFirstRunValueProofCommandPanel.css"');
    expect(globalStyles).not.toContain(".homepage-first-run-value-proof");
    expect(globalStyles).not.toContain(".homepage-first-run-critical-path");
    expect(panelStyles).toContain(".homepage-first-run-value-proof");
    expect(panelStyles).toContain(".homepage-first-run-critical-path");
    expect(panelStyles).toContain(".homepage-first-run-live-proof-audit");
    expect(panelStyles).toContain("@media (max-width: 760px)");
    expect(panelStyles).toContain("@media (max-width: 520px)");
  });

  test("places the first buyer decision route before the detailed proof workbench panels", () => {
    const appSource = readFileSync(new URL("../src/AppHome.tsx", import.meta.url), "utf8");
    const panelSource = readFileSync(new URL("../src/HomepageOutcomeSpinePanel.tsx", import.meta.url), "utf8");
    const panelStyles = readFileSync(new URL("../src/HomepageOutcomeSpinePanel.css", import.meta.url), "utf8");
    const globalStyles = readFileSync(new URL("../src/styles.css", import.meta.url), "utf8");
    const workbenchStart = appSource.indexOf('className="homepage-proof-workbench"');
    const spineMount = appSource.indexOf("<HomepageOutcomeSpinePanel", workbenchStart);
    const firstRunMount = appSource.indexOf("<HomepageFirstRunValueProofCommandPanel", workbenchStart);
    const valueLensMount = appSource.indexOf("<HomepageValueLensPanel", workbenchStart);

    expect(appSource).toContain('const HomepageOutcomeSpinePanel = lazy(() => import("./HomepageOutcomeSpinePanel"))');
    expect(workbenchStart).toBeGreaterThan(-1);
    expect(spineMount).toBeGreaterThan(workbenchStart);
    expect(firstRunMount).toBeGreaterThan(spineMount);
    expect(valueLensMount).toBeGreaterThan(firstRunMount);
    expect(appSource).toContain("valueLens={homepageValueLens}");
    expect(appSource).toContain("publishability={homepagePublishabilitySnapshot}");
    expect(appSource).toContain("reviewerHandoffKit={homepageReviewerHandoffKit}");
    expect(appSource).toContain("launchIntegrity={{");
    expect(appSource).toContain("workspace: workspaceDraft");
    expect(appSource).toContain("auditHref: buyerProofAuditHref");
    expect(appSource).toContain("gateHref: productionHardeningHref");
    expect(appSource).toContain("r: {");
    expect(appSource).toContain("f: BUYER_PILOT_PROOF_FIELDS");
    expect(appSource).toContain("oa: applyProofRepairDraft");
    expect(appSource).toContain("ov: verifyBuyerProofLinks");
    expect(panelSource).toContain("Workflow-to-decision route");
    expect(panelSource).toContain("First buyer decision route");
    expect(panelSource).toContain('import HomepageLaunchIntegrityPanel from "./HomepageLaunchIntegrityPanel"');
    expect(panelSource).toContain("buildHomepageOutcomeSpineReceipt");
    expect(panelSource).toContain("buildOutcomeSpineMarkdown");
    expect(panelSource).toContain("Route receipt");
    expect(panelSource).toContain("Verify route");
    expect(panelSource).toContain("receipt-verifier-request");
    expect(panelSource).toContain("value proof, public proof, buyer packet, and reviewer decision");
    expect(panelSource).toContain('import "./HomepageOutcomeSpinePanel.css"');
    expect(globalStyles).not.toContain(".homepage-outcome-spine");
    expect(panelStyles).toContain(".homepage-launch-integrity");
    expect(panelStyles).toContain(".homepage-launch-integrity-repair");
    expect(panelStyles).toContain(".homepage-launch-integrity-queue");
    expect(panelStyles).toContain(".homepage-outcome-spine");
    expect(panelStyles).toContain(".homepage-outcome-spine-steps::before");
    expect(panelStyles).toContain(".homepage-outcome-spine-receipt");
    expect(panelStyles).toContain("@media (max-width: 1180px)");
    expect(panelStyles).toContain("@media (max-width: 640px)");
  });

  test("routes claim trace data into role-specific buyer decision packets", () => {
    const appSource = readFileSync(new URL("../src/AppHome.tsx", import.meta.url), "utf8");
    const packetSource = readFileSync(new URL("../src/BuyerRoleDecisionPackets.tsx", import.meta.url), "utf8");
    const styles = readFileSync(new URL("../src/BuyerRoleDecisionPackets.css", import.meta.url), "utf8");
    const surfaceStart = appSource.indexOf("function BuyerProofCommandSurface");
    const surfaceEnd = appSource.indexOf("function routeActionAttrs", surfaceStart);
    const surfaceSource = appSource.slice(surfaceStart, surfaceEnd);

    expect(appSource).toContain('const BuyerRoleDecisionPackets = lazy(() => import("./BuyerRoleDecisionPackets"))');
    expect(packetSource).toContain('aria-label="Buyer role decision packets"');
    expect(surfaceSource).toContain("<BuyerRoleDecisionPackets evidenceTrace={evidenceTrace} evidenceTraceHref={evidenceTraceHref} onCopyText={onCopyText} />");
    expect(packetSource).toContain("buildBuyerRoleDecisionPackets");
    expect(packetSource).toContain("buildBuyerRoleDecisionPacketsMarkdown");
    expect(packetSource).toContain("Economic buyer");
    expect(packetSource).toContain("Technical evaluator");
    expect(packetSource).toContain("Security and procurement");
    expect(packetSource).toContain("Sponsor owner");
    expect(packetSource).toContain("Copy role packet");
    expect(packetSource).toContain("Download packets");
    expect(packetSource).toContain('aria-label="Buyer reviewer roles"');
    expect(packetSource).toContain('aria-label="Selected role proof lines"');
    expect(styles).toContain(".buyer-role-decision-packets");
    expect(styles).toContain(".buyer-role-selector");
    expect(styles).toContain(".buyer-role-selector {\n    grid-template-columns: repeat(2, minmax(0, 1fr));");

    const mobileRule = styles.indexOf(".buyer-role-decision-packets,\n  .buyer-role-decision-head,\n  .buyer-role-selector,\n  .buyer-role-decision-body {\n    grid-template-columns: 1fr;");
    const mobileStart = styles.lastIndexOf("@media", mobileRule);
    const mobileSource = styles.slice(mobileStart);
    expect(mobileRule).toBeGreaterThan(-1);
    expect(mobileSource).toContain(".buyer-role-decision-actions a,\n  .buyer-role-decision-actions button,\n  .buyer-role-decision-links a {\n    width: 100%;");
  });

  test("adds buyer objection rehearsal before residue audit", () => {
    const appSource = readFileSync(new URL("../src/AppHome.tsx", import.meta.url), "utf8");
    const objectionSource = readFileSync(new URL("../src/BuyerObjectionRehearsal.tsx", import.meta.url), "utf8");
    const styles = readFileSync(new URL("../src/BuyerObjectionRehearsal.css", import.meta.url), "utf8");
    const surfaceStart = appSource.indexOf("function BuyerProofCommandSurface");
    const surfaceEnd = appSource.indexOf("function routeActionAttrs", surfaceStart);
    const surfaceSource = appSource.slice(surfaceStart, surfaceEnd);
    const objectionMount = surfaceSource.indexOf("<BuyerObjectionRehearsal");
    const residueMount = surfaceSource.indexOf("<BuyerDemoResidueAuditPanel");

    expect(appSource).toContain('const BuyerObjectionRehearsal = lazy(() => import("./BuyerObjectionRehearsal"))');
    expect(objectionSource).toContain("buildBuyerObjectionRehearsal");
    expect(objectionSource).toContain("buildBuyerObjectionRehearsalMarkdown");
    expect(objectionSource).toContain("This still looks like a demo. Why should we trust it?");
    expect(objectionSource).toContain("Where is the measured value, not just the story?");
    expect(objectionSource).toContain("Copy objection");
    expect(objectionSource).toContain("Download rehearsal");
    expect(objectionSource).toContain('aria-label="Buyer objection rehearsal"');
    expect(objectionSource).toContain('aria-label="Selected objection evidence"');
    expect(surfaceSource).toContain("<BuyerObjectionRehearsal evidenceTrace={evidenceTrace} evidenceTraceHref={evidenceTraceHref} onCopyText={onCopyText} />");
    expect(objectionMount).toBeGreaterThan(-1);
    expect(residueMount).toBeGreaterThan(objectionMount);
    expect(styles).toContain(".buyer-objection-rehearsal");
    expect(styles).toContain(".buyer-objection-list");
    expect(styles).toContain(".buyer-objection-list {\n    grid-template-columns: repeat(3, minmax(0, 1fr));");

    const mobileRule = styles.indexOf(".buyer-objection-rehearsal,\n  .buyer-objection-head,\n  .buyer-objection-list,\n  .buyer-objection-detail {\n    grid-template-columns: 1fr;");
    const mobileStart = styles.lastIndexOf("@media", mobileRule);
    const mobileSource = styles.slice(mobileStart);
    expect(mobileRule).toBeGreaterThan(-1);
    expect(mobileSource).toContain(".buyer-objection-actions a,\n  .buyer-objection-actions button,\n  .buyer-objection-links a {\n    width: 100%;");
  });

  test("turns production hardening into an owner-ready recovery kit", () => {
    const panelSource = readFileSync(new URL("../src/ProductionHardeningPanel.tsx", import.meta.url), "utf8");
    const hardeningSource = readFileSync(new URL("../src/productionHardening.ts", import.meta.url), "utf8");
    const styles = readFileSync(new URL("../src/styles.css", import.meta.url), "utf8");

    expect(hardeningSource).toContain("ProductionHardeningRecoveryKit");
    expect(hardeningSource).toContain("buildRecoveryKit");
    expect(hardeningSource).toContain("issueBody");
    expect(hardeningSource).toContain("Global release recovery kit");
    expect(hardeningSource).toContain("Recovery issue queue");
    expect(hardeningSource).toContain("Do not share externally until every P0 recovery ticket is verified");
    expect(panelSource).toContain('aria-label="Global release recovery kit"');
    expect(panelSource).toContain('aria-label="Top release recovery issue"');
    expect(panelSource).toContain('aria-label="Recovery issue queue"');
    expect(panelSource).toContain("Copy top issue");
    expect(panelSource).toContain("global-release-recovery-kit.csv");
    expect(panelSource).toContain("global-release-recovery-kit.json");
    expect(styles).toContain(".production-hardening-recovery-kit");
    expect(styles).toContain(".production-hardening-recovery-head");
    expect(styles).toContain(".production-hardening-recovery-issues");
    expect(styles).toContain(".production-hardening-recovery-issues {\n  display: grid;\n  grid-template-columns: repeat(4, minmax(0, 1fr));");

    const mobileRule = styles.indexOf(".production-hardening-checks,\n  .production-hardening-action-packet > div,\n  .production-hardening-recovery-head,\n  .production-hardening-recovery-issues,");
    const mobileStart = styles.lastIndexOf("@media", mobileRule);
    const mobileSource = styles.slice(mobileStart);
    expect(mobileRule).toBeGreaterThan(-1);
    expect(mobileSource).toContain(".production-hardening-recovery-actions .icon-link {\n    width: 100%;");
  });

  test("adds a cross-workspace operator next move before detailed proof panels", () => {
    const appSource = readFileSync(new URL("../src/AppHome.tsx", import.meta.url), "utf8");
    const builderSource = readFileSync(new URL("../src/homepageOperatorNextMove.ts", import.meta.url), "utf8");
    const panelSource = readFileSync(new URL("../src/HomepageOperatorNextMovePanel.tsx", import.meta.url), "utf8");
    const trustBuilderSource = readFileSync(new URL("../src/homepagePublicTrustScan.ts", import.meta.url), "utf8");
    const trustPanelSource = readFileSync(new URL("../src/HomepagePublicTrustScanPanel.tsx", import.meta.url), "utf8");
    const launchIntegritySource = readFileSync(new URL("../src/HomepageLaunchIntegrityPanel.tsx", import.meta.url), "utf8");
    const outcomeSpineSource = readFileSync(new URL("../src/HomepageOutcomeSpinePanel.tsx", import.meta.url), "utf8");
    const styles = readFileSync(new URL("../src/HomepageOperatorNextMovePanel.css", import.meta.url), "utf8");
    const trustStyles = readFileSync(new URL("../src/HomepagePublicTrustScanPanel.css", import.meta.url), "utf8");
    const outcomeStyles = readFileSync(new URL("../src/HomepageOutcomeSpinePanel.css", import.meta.url), "utf8");
    const operatorMount = outcomeSpineSource.indexOf("<HomepageOperatorNextMovePanel");
    const trustMount = outcomeSpineSource.indexOf("<HomepagePublicTrustScanPanel", operatorMount);
    const launchIntegrityMount = outcomeSpineSource.indexOf("<HomepageLaunchIntegrityPanel", trustMount);
    const detailedRoute = outcomeSpineSource.indexOf('className={cx("homepage-outcome-spine"', launchIntegrityMount);

    expect(appSource).not.toContain('const HomepageOperatorNextMovePanel = lazy(() => import("./HomepageOperatorNextMovePanel"))');
    expect(appSource).not.toContain('const HomepagePublicTrustScanPanel = lazy(() => import("./HomepagePublicTrustScanPanel"))');
    expect(outcomeSpineSource).toContain('import HomepageOperatorNextMovePanel from "./HomepageOperatorNextMovePanel"');
    expect(outcomeSpineSource).toContain('import HomepagePublicTrustScanPanel from "./HomepagePublicTrustScanPanel"');
    expect(outcomeSpineSource).toContain('import HomepageLaunchIntegrityPanel from "./HomepageLaunchIntegrityPanel"');
    expect(operatorMount).toBeGreaterThan(-1);
    expect(trustMount).toBeGreaterThan(operatorMount);
    expect(launchIntegrityMount).toBeGreaterThan(trustMount);
    expect(detailedRoute).toBeGreaterThan(launchIntegrityMount);
    expect(outcomeSpineSource).toContain("valueLens={valueLens}");
    expect(outcomeSpineSource).toContain("publishability={publishability}");
    expect(outcomeSpineSource).toContain("outcomeArtifact={outcomeArtifact}");
    expect(outcomeSpineSource).toContain("reviewerHandoffKit={reviewerHandoffKit}");
    expect(outcomeSpineSource).toContain("launchIntegrity: HomepageLaunchIntegrityProps");
    expect(outcomeSpineSource).toContain("workspace={launchIntegrity.workspace}");
    expect(outcomeSpineSource).toContain('workflowIntakeHref={launchIntegrity.workflowHref ?? "#quick-workflow-intake"}');
    expect(outcomeSpineSource).toContain("productionHardeningHref={launchIntegrity.gateHref}");
    expect(outcomeSpineSource).toContain("proofRepair={launchIntegrity.r}");
    expect(builderSource).toContain("buildHomepageOperatorNextMove");
    expect(builderSource).toContain("buildPublishabilityCandidate");
    expect(builderSource).toContain("buildBuyerPacketCandidate");
    expect(builderSource).toContain("buildReviewerHandoffCandidate");
    expect(panelSource).toContain('aria-label="Operator next move actions"');
    expect(panelSource).toContain('aria-label="Owner command"');
    expect(panelSource).toContain('aria-label="Acceptance criteria"');
    expect(panelSource).toContain('aria-label="Operator candidate queue"');
    expect(panelSource).toContain("Copy command");
    expect(panelSource).toContain("Export Markdown");
    expect(panelSource).toContain("Export CSV");
    expect(panelSource).toContain("operator-next-move.md");
    expect(panelSource).toContain("operator-next-move.csv");
    expect(styles).toContain(".homepage-operator-next-move");
    expect(styles).toContain(".homepage-operator-next-move-queue");
    expect(trustBuilderSource).toContain("buildHomepagePublicTrustScan");
    expect(trustBuilderSource).toContain("buyerQuestion");
    expect(trustBuilderSource).toContain("HomepagePublicTrustBuyerAnswer");
    expect(trustBuilderSource).toContain("answerDeckSummary");
    expect(trustBuilderSource).toContain("visitorPromise");
    expect(trustPanelSource).toContain('aria-label="Public trust scan actions"');
    expect(trustPanelSource).toContain('aria-label="First public buyer question"');
    expect(trustPanelSource).toContain('aria-label="Public publish rule"');
    expect(trustPanelSource).toContain('aria-label="Buyer question answer deck"');
    expect(trustPanelSource).toContain('aria-label="Public trust checks"');
    expect(trustPanelSource).toContain("Buyer answer deck");
    expect(trustPanelSource).toContain("Copy scan");
    expect(trustPanelSource).toContain("public-trust-scan.md");
    expect(trustPanelSource).toContain("public-trust-scan.csv");
    expect(launchIntegritySource).toContain("buildProductionHardeningSnapshot");
    expect(launchIntegritySource).toContain("buildProductionHardeningDemoResidueAudit");
    expect(launchIntegritySource).toContain("buildLaunchIntegrityProofRepairTarget");
    expect(launchIntegritySource).toContain("buildLaunchIntegrityRepairProjection");
    expect(launchIntegritySource).toContain("buildLaunchIntegrityProofSlotAudit");
    expect(launchIntegritySource).toContain('aria-label="Launch integrity triage"');
    expect(launchIntegritySource).toContain('aria-label="Launch integrity repair control"');
    expect(launchIntegritySource).toContain('aria-label="Projected launch gate after repair"');
    expect(launchIntegritySource).toContain('aria-label="Public proof slot audit"');
    expect(launchIntegritySource).toContain("Repair impact");
    expect(launchIntegritySource).toContain("Public proof slot audit");
    expect(launchIntegritySource).toContain("Paste replacement URL");
    expect(launchIntegritySource).toContain("Apply & verify");
    expect(launchIntegritySource).toContain('aria-label="First launch recovery issue"');
    expect(launchIntegritySource).toContain('aria-label="Reference residue audit"');
    expect(launchIntegritySource).toContain("Copy top issue");
    expect(launchIntegritySource).toContain("global-release-recovery-kit.csv");
    expect(launchIntegritySource).toContain("global-release-recovery-kit.json");
    expect(trustStyles).toContain(".homepage-public-trust-scan");
    expect(trustStyles).toContain(".homepage-public-trust-scan-answer-deck");
    expect(trustStyles).toContain(".homepage-public-trust-scan-answers");
    expect(trustStyles).toContain(".homepage-public-trust-scan-checks");
    expect(outcomeStyles).toContain(".homepage-launch-integrity");
    expect(outcomeStyles).toContain(".homepage-launch-integrity-repair");
    expect(outcomeStyles).toContain(".homepage-launch-integrity-repair-impact");
    expect(outcomeStyles).toContain(".homepage-launch-integrity-proof-slots");
    expect(outcomeStyles).toContain(".homepage-launch-integrity-proof-slot-list");
    expect(outcomeStyles).toContain(".homepage-launch-integrity-queue");

    const mobileRule = styles.indexOf(".homepage-operator-next-move,\n  .homepage-operator-next-move-command,\n  .homepage-operator-next-move-acceptance,\n  .homepage-operator-next-move-queue {\n    grid-template-columns: 1fr;");
    const mobileStart = styles.lastIndexOf("@media", mobileRule);
    const mobileSource = styles.slice(mobileStart);
    expect(mobileRule).toBeGreaterThan(-1);
    expect(mobileSource).toContain(".homepage-operator-next-move-primary,\n  .homepage-operator-next-move-link {\n    width: 100%;");

    const trustMobileRule = trustStyles.indexOf(".homepage-public-trust-scan,\n  .homepage-public-trust-scan-answer-deck,\n  .homepage-public-trust-scan-answers,\n  .homepage-public-trust-scan-checks {\n    grid-template-columns: 1fr;");
    const trustMobileStart = trustStyles.lastIndexOf("@media", trustMobileRule);
    const trustMobileSource = trustStyles.slice(trustMobileStart);
    expect(trustMobileRule).toBeGreaterThan(-1);
    expect(trustMobileSource).toContain(".homepage-public-trust-scan-primary,\n  .homepage-public-trust-scan-link {\n    width: 100%;");

    const launchMobileRule = outcomeStyles.indexOf(".homepage-launch-integrity-actions,\n  .homepage-launch-integrity-queue,\n  .homepage-launch-integrity-repair-actions {\n    display: grid;\n    grid-template-columns: 1fr;");
    const launchMobileStart = outcomeStyles.lastIndexOf("@media", launchMobileRule);
    const launchMobileSource = outcomeStyles.slice(launchMobileStart);
    expect(launchMobileRule).toBeGreaterThan(-1);
    expect(launchMobileSource).toContain(".homepage-launch-integrity-primary,\n  .homepage-launch-integrity-link,\n  .homepage-launch-integrity-repair-actions a,\n  .homepage-launch-integrity-repair-actions button {\n    width: 100%;");
  });

  test("lets the buyer proof repair queue replace proof URLs inline", () => {
    const appSource = readFileSync(new URL("../src/AppHome.tsx", import.meta.url), "utf8");
    const panelSource = readFileSync(new URL("../src/BuyerProofRepairQueuePanel.tsx", import.meta.url), "utf8");
    const styles = readFileSync(new URL("../src/BuyerProofRepairQueuePanel.css", import.meta.url), "utf8");

    expect(panelSource).toContain('className="buyer-proof-repair-execution"');
    expect(panelSource).toContain("function proofKeyForWorkOrder");
    expect(panelSource).toContain('if (id === "public-product") return "targetUrl"');
    expect(panelSource).toContain('if (id === "work-order") return "workOrderEvidenceUrl"');
    expect(panelSource).toContain('if (id === "measured-run") return "pilotEvidenceUrl"');
    expect(panelSource).toContain('if (id === "walkthrough") return "videoUrl"');
    expect(panelSource).toContain('if (id === "protopedia") return "protopediaUrl"');
    expect(panelSource).toContain("proofReplacementDrafts");
    expect(panelSource).toContain("currentProofValue(key)");
    expect(panelSource).toContain("onProofIntakeChange(patch.proofIntake)");
    expect(panelSource).toContain("onApplyProofReplacement({ [key]: value })");
    expect(panelSource).toContain('proofVerifyStatus !== "checking"');
    expect(panelSource).toContain('className="buyer-proof-repair-inline-input"');
    expect(panelSource).toContain("Apply & verify");
    expect(panelSource).toContain("Checking");
    expect(panelSource).toContain("proofKey ? (");
    expect(panelSource).toContain("<a href={order.inputHref}>");
    expect(appSource).toContain("async function applyProofReplacementAndVerify");
    expect(appSource).toContain("await verifyBuyerProofLinksWithIntake(nextProofIntake)");
    expect(appSource).toContain("onApplyProofReplacement={applyProofReplacementAndVerify}");
    expect(appSource).toContain("proofVerifyStatus={proofVerifyStatus}");
    expect(styles).toContain(".buyer-proof-repair-inline-input");
    expect(styles).toContain(".buyer-proof-repair-inline-input input");
    expect(styles).toContain(".buyer-proof-repair-inline-input button");

    const mobileStart = styles.indexOf("@media (max-width: 760px)");
    const nextMediaStart = styles.indexOf("@media", mobileStart + 1);
    const mobileSource = styles.slice(mobileStart, nextMediaStart === -1 ? undefined : nextMediaStart);
    expect(mobileSource).toContain(".buyer-proof-repair-inline-input {\n    grid-template-columns: 1fr;");
    expect(mobileSource).toContain(".buyer-proof-repair-main .buyer-proof-repair-inline-input button {\n    width: 100%;");
  });

  test("places the reference mode bridge before the blocked proof workbench", () => {
    const source = readFileSync(new URL("../src/AppHome.tsx", import.meta.url), "utf8");
    const bridgeSource = readFileSync(new URL("../src/HomepageReferenceModeBridge.tsx", import.meta.url), "utf8");
    const proofPreviewStart = source.indexOf("<ProofTransformationHero");
    const bridgeMount = source.indexOf("<HomepageReferenceModeBridge", proofPreviewStart);
    const workbenchStart = source.indexOf('className="homepage-proof-workbench"', bridgeMount);

    expect(source).toContain('lazy(() => import("./HomepageReferenceModeBridge"))');
    expect(proofPreviewStart).toBeGreaterThan(-1);
    expect(bridgeMount).toBeGreaterThan(proofPreviewStart);
    expect(workbenchStart).toBeGreaterThan(bridgeMount);
    expect(bridgeSource).toContain("Reference mode");
    expect(bridgeSource).toContain("not a sendable buyer claim");
    expect(bridgeSource).toContain("Paste your workflow");
    expect(bridgeSource).toContain("Replace proof URLs");
    expect(bridgeSource).toContain("Review send brief");
    expect(bridgeSource).not.toMatch(/demo/i);
  });

  test("keeps the public Agent Card proof receipt language reviewer-facing", () => {
    const source = readFileSync(new URL("../server/index.ts", import.meta.url), "utf8");
    const receiptStart = source.indexOf('id: "demo.receipt"');
    const receiptEnd = source.indexOf('id: "autonomy.ledger"', receiptStart);
    const receiptSkillSource = source.slice(receiptStart, receiptEnd);

    expect(receiptStart).toBeGreaterThan(-1);
    expect(receiptEnd).toBeGreaterThan(receiptStart);
    expect(receiptSkillSource).toContain("Seal the reviewer proof receipt");
    expect(receiptSkillSource).toContain("Reviewer Route Lock");
    expect(receiptSkillSource).toContain("reviewer-proof");

    expect(receiptSkillSource).not.toContain("Seal the judge demo receipt");
    expect(receiptSkillSource).not.toContain("Judge Route Lock");
    expect(receiptSkillSource).not.toContain("\"judge-proof\"");
  });

  test("keeps public Agent Card route orchestration language reviewer-facing", () => {
    const source = readFileSync(new URL("../server/index.ts", import.meta.url), "utf8");
    const commandStart = source.indexOf("id: JUDGE_COMMAND_SKILL_ID");
    const rehearsalStart = source.indexOf('id: "judge.rehearsal"', commandStart);
    const rehearsalEnd = source.indexOf('id: "winner.packet"', rehearsalStart);
    const routeSkillSource = source.slice(commandStart, rehearsalEnd);

    expect(commandStart).toBeGreaterThan(-1);
    expect(rehearsalStart).toBeGreaterThan(commandStart);
    expect(rehearsalEnd).toBeGreaterThan(rehearsalStart);
    expect(routeSkillSource).toContain("Build the reviewer command center");
    expect(routeSkillSource).toContain("Rehearse the 90-second reviewer run");
    expect(routeSkillSource).toContain("Reviewer Command");
    expect(routeSkillSource).toContain("Reviewer Concierge");
    expect(routeSkillSource).toContain("reviewer-command");
    expect(routeSkillSource).toContain("reviewer-rehearsal");

    expect(routeSkillSource).not.toContain("Build the judge command center");
    expect(routeSkillSource).not.toContain("Rehearse the 90-second judge run");
    expect(routeSkillSource).not.toContain("Judge Command");
    expect(routeSkillSource).not.toContain("Demo Concierge");
    expect(routeSkillSource).not.toContain("\"judge-command\"");
    expect(routeSkillSource).not.toContain("\"demo\"");
  });
});
